CREATE DATABASE GYM;
DROP DATABASE GYM;

CREATE DATABASE YOUTUBE;
DROP DATABASE YOUTUBE;

CREATE DATABASE PRODUCTS;
DROP DATABASE products;

CREATE DATABASE EQUIPMENTS;
DROP DATABASE EQUIPMENTS;

CREATE SCHEMA SUBSCRIPTION;
DROP SCHEMA SUBSCRIPTION;

SHOW DATABASES;